# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJa9iihMdjw0EqkBrvvcpjcBgryEFVqi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('/content/Data.csv')
df.head()

df.tail()

df.shape

df.columns

df.dtypes

df.info()

df.describe()

df = df.fillna(method='ffill')
df.head()

df.isna().sum().any()

df['Country Name'].unique()

df['Country Code'].unique()

df.columns

cols = ['1990 [YR1990]', '2000 [YR2000]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]']

for i in cols:
    fig = plt.figure(figsize=(5, 5))
    plt.hist(df[i], color="#B22222", bins=10, edgecolor='black')
    plt.xlabel(i)
    plt.show()

years = df.columns[1:]

total_values = df[years].sum()

plt.figure(figsize=(30, 30))
plt.bar(years, total_values,color='#191970')
plt.xlabel('Total Values')
plt.ylabel('year',size = 20)
plt.title('Total Values in Each Year',size = 20)
plt.show()